Premier commit jeu
pH0xe/tablut pull request #1
Opened 2021-05-17 13:22 UTC by ELCALVO

2021-05-17 13:37 UTC, pH0xe requested changes

2021-05-17 13:37 UTC, pH0xe commented on src/modele/Plateau.java
> +    public Pion noir1;
oskour non

2021-05-17 13:37 UTC, pH0xe commented on src/modele/Pion.java
> +        etat = EtatPion.INACTIF;
mieux de mettre EtatPion en parametre au moins tu peux faire ce que tu veux

2021-05-17 13:37 UTC, pH0xe commented on src/modele/Plateau.java
> +        blanc1 = new Pion(TypePion.BLANC, new Point(2, 4));
Ils ont pas besoin d'etre connu ... tu add directement des new Pions

2021-05-17 14:22 UTC, pH0xe requested changes

2021-05-17 14:22 UTC, pH0xe commented on src/modele/Pion.java
> +        etat = EtatPion.INACTIF;
toujours pas, mettre etatPion en parametre de changerEtat

2021-05-18 07:17 UTC, pH0xe requested changes

2021-05-18 07:17 UTC, pH0xe commented on src/modele/Plateau.java
> +        this.blancs.add(new Pion(TypePion.BLANC, new Point(2, 4)));
Vous pouvez faire une boucle pour les instancié ca sera mieux

2021-05-18 07:17 UTC, pH0xe commented on src/modele/Plateau.java
> +    public List<Point> getCasesAccessibles(Pion pion){
Ne marche pas askip

2021-05-18 07:44 UTC, pH0xe requested changes

2021-05-18 07:44 UTC, pH0xe commented on src/modele/Plateau.java
> +    public Jeu jeu;
Plateau ne connais pas jeu.
c'est Jeu qui possede un plateu (et peu y acceder)

2021-05-18 13:12 UTC, pH0xe requested changes

2021-05-18 13:12 UTC, pH0xe commented on src/controleur/CollecteurEvenements.java
> +    void demarrerJeu(int l, int c, String player1, String player2);
Pourquoi cette méthode ? elle existe mais pas sans paramètre

2021-05-18 13:12 UTC, pH0xe commented on src/modele/Jeu.java
> +    Plateau pt;
private

2021-05-18 13:12 UTC, pH0xe commented on src/modele/Jeu.java
> +        return (roiC == 0 && roiL == 0 || roiC == 0 && roiL == 8 || roiC == 8 && roiL == 0 || roiC == 8 && roiL == 8);
mettre des parenthese au bon endroits sinon ca peut faire des truc cheloux

2021-05-18 13:12 UTC, pH0xe commented on src/modele/Plateau.java
> +    public int[][] cases;
ca serait peut etre mieux de faire un tableau de pion ? Je propose
avec du coup soit un pion soit null

2021-05-18 13:12 UTC, pH0xe commented on src/modele/Plateau.java
> +    // Sinon idee : un array list des cases auxquelles un pion peut se deplacer; util pour highlighting des cases
C'est le principe de cette fonction. On veut toute les cases vers ou on peut aller a partir d'un pion

2021-05-18 13:12 UTC, pH0xe commented on src/modele/Plateau.java
> +            this.blancs.remove(pion);
Pourquoi le remove pour le add ensuite ? c'est un objet donc il est update dans la liste automatiquement

2021-05-18 13:21 UTC, nishithprg commented on src/modele/Jeu.java
> +        return (roiC == 0 && roiL == 0 || roiC == 0 && roiL == 8 || roiC == 8 && roiL == 0 || roiC == 8 && roiL == 8);
J'ai hesite de mettre des parentheses a cet endroit.

2021-05-18 13:22 UTC, nishithprg commented on src/controleur/CollecteurEvenements.java
> +    void demarrerJeu(int l, int c, String player1, String player2);
J'ai essaye de faire un truc mais jai abandonne. Jai oublie d'enlever

2021-05-18 13:37 UTC, nishithprg commented on src/modele/Plateau.java
> +            this.blancs.remove(pion);
Tu as raison, j'y ai pas pense.

2021-05-19 07:16 UTC, pH0xe approved these changes

2021-05-19 07:17 UTC, merged